language: d
sudo: false
dist: bionic


matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.089.1
    - d: dmd-2.088.1
    - d: dmd-2.087.1
    - d: ldc-1.18.0
  allow_failures:
    - d: dmd-nightly


addons:
  apt:
    packages:
      - libclang-dev
      - g++


install:
  - gem install bundler -v 1.17.3
  - bundle install


env:
  global:
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/llvm-6.0/lib

script:
  - ./ci.sh


after_success:
 - bash <(curl -s https://codecov.io/bash)
