language: d
sudo: false
dist: xenial

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.088.1
    - d: dmd-2.087.1
    - d: dmd-2.086.1
  allow_failures:
    - d: dmd-nightly


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libclang-6.0-dev
      - g++-7


install:
  - gem install bundler -v 1.17.3
  - bundle install


script:
  - ./ci.sh


after_success:
 - bash <(curl -s https://codecov.io/bash)
